organization:
    id: d0fc62ae-1f4a-4037-8ccb-d357adfdfda6
    name: Qredence
project:
    id: ad1f3be2-d37b-4eb4-9078-dc03f66abb36
    slug: circleci/SomxVLJYMpo86z6XUrZBUq/NNv4p21ouvwjCDRSiamu5o
    name: fleet-agent
