/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RunStatus = "idle" | "queued" | "running" | "completed" | "failed" | "cancelled";
export type StepPhase = "understanding" | "planning" | "research" | "analysis" | "critique" | "synthesis";
export type StepStatus = "pending" | "running" | "completed" | "failed";
export type DecisionStatus = "considering" | "accepted" | "rejected";
export type ToolCallStatus = "pending" | "running" | "completed" | "failed";
export type SourceType = "web" | "document" | "repository" | "database" | "other";
export type ArtifactStatus = "generating" | "ready" | "failed";

/**
 * Public, user-safe agent process state synchronized to the browser via AG-UI STATE_SNAPSHOT / STATE_DELTA. Never contains raw model chain-of-thought or provider payloads.
 */
export interface AgentWorkspaceState {
  /**
   * Contract version. Any breaking shape change increments it.
   */
  schemaVersion: 1;
  threadId: string;
  run: Run;
  steps: ProcessStep[];
  decisions: ProcessDecision[];
  toolCalls: ToolExecution[];
  sources: AgentSource[];
  artifacts: AgentArtifact[];
  metrics: RunMetrics;
  /**
   * User-safe caveats produced at run completion (uncertainty, limitations, forced-submit diagnostics).
   */
  caveats?: string[];
}
export interface Run {
  id: string;
  status: RunStatus;
  startedAt?: string;
  finishedAt?: string;
  activeStepId?: string;
  /**
   * DSPy ReActV2 termination reason, e.g. submit, forced_submit, max_iters, empty_tool_calls, parse_error, context_window_exceeded.
   */
  terminationReason?: string;
  /**
   * Stable public error code. Never a raw exception string.
   */
  errorCode?: string;
  toolCallCount: number;
}
export interface ProcessStep {
  id: string;
  parentId?: string;
  phase: StepPhase;
  title: string;
  /**
   * Explicitly written for the user. Never raw model chain-of-thought.
   */
  publicSummary?: string;
  status: StepStatus;
  startedAt?: string;
  finishedAt?: string;
  durationMs?: number;
  toolCallIds: string[];
  sourceIds: string[];
  artifactIds: string[];
}
export interface ProcessDecision {
  id: string;
  title: string;
  alternatives: string[];
  selected?: string;
  /**
   * User-safe rationale. Never raw model chain-of-thought.
   */
  publicRationale?: string;
  status: DecisionStatus;
}
export interface ToolExecution {
  id: string;
  name: string;
  status: ToolCallStatus;
  /**
   * Redacted, size-limited preview of tool arguments.
   */
  inputPreview?: string;
  /**
   * Redacted, size-limited preview of the tool result.
   */
  outputPreview?: string;
  /**
   * Public error message. Never a stack trace.
   */
  errorMessage?: string;
  startedAt?: string;
  finishedAt?: string;
  durationMs?: number;
}
export interface AgentSource {
  id: string;
  title: string;
  sourceType: SourceType;
  uri?: string;
  excerpt?: string;
  toolCallId?: string;
}
export interface AgentArtifact {
  id: string;
  name: string;
  mediaType: string;
  sizeBytes?: number;
  /**
   * Controlled URL or artifact reference. Never a server filesystem path.
   */
  downloadUrl?: string;
  status: ArtifactStatus;
}
export interface RunMetrics {
  durationMs?: number;
  inputTokens?: number;
  outputTokens?: number;
  totalTokens?: number;
  toolCallCount: number;
  modelCallCount?: number;
}
