/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Everything the client needs to restore a thread after reload or switch. Served by GET /api/threads/{thread_id}/bootstrap.
 */
export interface ThreadBootstrap {
  /**
   * Contract version. Any breaking shape change increments it.
   */
  schemaVersion: 1;
  thread: ThreadOut;
  messageRepository: MessageRepository;
  /**
   * Legacy flat message list kept for older clients; new clients use messageRepository.
   */
  messages: {
    [k: string]: unknown;
  }[];
  /**
   * Latest AgentWorkspaceState snapshot for the process panel, or null.
   */
  agentState: {
    [k: string]: unknown;
  } | null;
  latestRun: LatestRun | null;
}
export interface ThreadOut {
  id: string;
  projectId: string;
  title: string;
  status: string;
  lastRunId: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Branch repository in the current bootstrap format.
 */
export interface MessageRepository {
  headId: string | null;
  messages: MessageStorageEntry[];
}
export interface MessageStorageEntry {
  id: string;
  parentId: string | null;
  /**
   * Wire format of the stored branch node. Known values: "ag-ui/v1" (AG-UI messages) and "aui/v0" (assistant-ui nodes); clients validate before decoding, and the repository passes persisted values through untouched.
   */
  format: string;
  /**
   * The assistant-ui message node as persisted.
   */
  content: {
    [k: string]: unknown;
  };
  /**
   * Run configuration captured with the message, when present.
   */
  runConfig?: {
    [k: string]: unknown;
  };
}
export interface LatestRun {
  id: string;
  status: string;
  /**
   * One of the public termination reasons, or null while in flight.
   */
  terminationReason: string | null;
  /**
   * Stable public error code. Never a raw exception string.
   */
  errorCode: string | null;
}
