import type { ExportedMessageRepositoryItem } from '@assistant-ui/react'

export const DEFAULT_THREAD_TITLE = 'New conversation'
const MAX_THREAD_TITLE_LENGTH = 48

/**
 * Keep automatic titles predictable and useful in the narrow thread list.
 * Titles are derived from the first visible line rather than generated by the
 * model, so renaming never adds latency or another provider request.
 */
export function deriveThreadTitle(query: string): string {
  const firstVisibleLine = query
    .split(/\r?\n/)
    .map((line) => line.replace(/\s+/g, ' ').trim())
    .find(Boolean)

  if (!firstVisibleLine) return DEFAULT_THREAD_TITLE
  if (firstVisibleLine.length <= MAX_THREAD_TITLE_LENGTH) return firstVisibleLine

  return `${firstVisibleLine.slice(0, MAX_THREAD_TITLE_LENGTH - 1).trimEnd()}…`
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

/** Extract only visible text from an assistant-ui user message. */
export function getUserMessageText(
  message: ExportedMessageRepositoryItem['message'],
): string {
  if (message.role !== 'user' || !Array.isArray(message.content)) return ''

  return message.content
    .filter(isRecord)
    .filter((part) => part.type === 'text' && typeof part.text === 'string')
    .map((part) => part.text as string)
    .join('\n')
}
