# generated by datamodel-codegen:
#   filename:  agent-workspace-state.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint


class RunStatus(StrEnum):
    idle = "idle"
    queued = "queued"
    running = "running"
    interrupted = "interrupted"
    completed = "completed"
    failed = "failed"
    cancelled = "cancelled"


class Run(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    status: RunStatus = Field(..., title="RunStatus")
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    activeStepId: str | None = None
    terminationReason: str | None = Field(
        None,
        description="DSPy ReActV2 termination reason, e.g. submit, forced_submit, max_iters, empty_tool_calls, parse_error, context_window_exceeded.",
    )
    errorCode: str | None = Field(
        None, description="Stable public error code. Never a raw exception string."
    )
    toolCallCount: conint(ge=0)


class StepPhase(StrEnum):
    understanding = "understanding"
    planning = "planning"
    research = "research"
    analysis = "analysis"
    critique = "critique"
    synthesis = "synthesis"


class StepStatus(StrEnum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"


class ProcessStep(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    parentId: str | None = None
    phase: StepPhase = Field(..., title="StepPhase")
    title: str
    publicSummary: str | None = Field(
        None,
        description="Explicitly written for the user. Never raw model chain-of-thought.",
    )
    status: StepStatus = Field(..., title="StepStatus")
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    durationMs: conint(ge=0) | None = None
    toolCallIds: list[str]
    sourceIds: list[str]
    artifactIds: list[str]


class DecisionStatus(StrEnum):
    considering = "considering"
    accepted = "accepted"
    rejected = "rejected"


class ProcessDecision(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    title: str
    alternatives: list[str]
    selected: str | None = None
    publicRationale: str | None = Field(
        None, description="User-safe rationale. Never raw model chain-of-thought."
    )
    status: DecisionStatus = Field(..., title="DecisionStatus")


class ToolCallStatus(StrEnum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"


class ToolExecution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    status: ToolCallStatus = Field(..., title="ToolCallStatus")
    inputPreview: str | None = Field(
        None, description="Redacted, size-limited preview of tool arguments."
    )
    outputPreview: str | None = Field(
        None, description="Redacted, size-limited preview of the tool result."
    )
    errorMessage: str | None = Field(
        None, description="Public error message. Never a stack trace."
    )
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    durationMs: conint(ge=0) | None = None


class SourceType(StrEnum):
    web = "web"
    document = "document"
    repository = "repository"
    database = "database"
    other = "other"


class AgentSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    title: str
    sourceType: SourceType = Field(..., title="SourceType")
    uri: str | None = None
    excerpt: str | None = None
    toolCallId: str | None = None


class ArtifactStatus(StrEnum):
    generating = "generating"
    ready = "ready"
    failed = "failed"


class AgentArtifact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    mediaType: str
    sizeBytes: conint(ge=0) | None = None
    downloadUrl: str | None = Field(
        None,
        description="Controlled URL or artifact reference. Never a server filesystem path.",
    )
    status: ArtifactStatus = Field(..., title="ArtifactStatus")


class RunMetrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    durationMs: conint(ge=0) | None = None
    inputTokens: conint(ge=0) | None = None
    outputTokens: conint(ge=0) | None = None
    totalTokens: conint(ge=0) | None = None
    toolCallCount: conint(ge=0)
    modelCallCount: conint(ge=0) | None = None


class AgentWorkspaceState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schemaVersion: Literal[1] = Field(
        ..., description="Contract version. Any breaking shape change increments it."
    )
    threadId: str
    run: Run = Field(..., title="Run")
    steps: list[ProcessStep]
    decisions: list[ProcessDecision]
    toolCalls: list[ToolExecution]
    sources: list[AgentSource]
    artifacts: list[AgentArtifact]
    metrics: RunMetrics = Field(..., title="RunMetrics")
    caveats: list[str] | None = Field(
        None,
        description="User-safe caveats produced at run completion (uncertainty, limitations, forced-submit diagnostics).",
    )
