# generated by datamodel-codegen:
#   filename:  agent-capabilities.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class AgentCapabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent_mode: Literal["fixtures", "engine"]
