# generated by datamodel-codegen:
#   filename:  thread-bootstrap.schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class ThreadOut(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    projectId: str
    title: str
    status: str
    lastRunId: str | None
    createdAt: str
    updatedAt: str


class MessageStorageEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    parentId: str | None
    format: str = Field(
        ...,
        description='Wire format of the stored branch node. Known values: "ag-ui/v1" (AG-UI messages) and "aui/v0" (assistant-ui nodes); clients validate before decoding, and the repository passes persisted values through untouched.',
    )
    content: dict[str, Any] = Field(
        ..., description="The assistant-ui message node as persisted."
    )
    runConfig: dict[str, Any] | None = Field(
        None, description="Run configuration captured with the message, when present."
    )


class LatestRun(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    status: str
    terminationReason: str | None = Field(
        ...,
        description="One of the public termination reasons, or null while in flight.",
    )
    errorCode: str | None = Field(
        ..., description="Stable public error code. Never a raw exception string."
    )


class MessageRepository(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    headId: str | None
    messages: list[MessageStorageEntry]


class ThreadBootstrap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schemaVersion: Literal[1] = Field(
        ..., description="Contract version. Any breaking shape change increments it."
    )
    thread: ThreadOut
    messageRepository: MessageRepository = Field(
        ..., description="Branch repository in the current bootstrap format."
    )
    messages: list[dict[str, Any]] = Field(
        ...,
        description="Legacy flat message list kept for older clients; new clients use messageRepository.",
    )
    agentState: dict[str, Any] | None = Field(
        ...,
        description="Latest AgentWorkspaceState snapshot for the process panel, or null.",
    )
    latestRun: LatestRun | None
